#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use FindBin;
use lib ( "$FindBin::RealBin/../lib", );
use Mhj::CLI;
Mhj::CLI->new->run;
# use lib ( "$FindBin::RealBin/../lib/",
#     "$FindBin::RealBin/../local/lib/perl5/" );
